### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by fkamaral** [sigboe/pie-galaxy#14]
Guys, the install was ok, but when I try to authenticate, using email and password it says authentication unsuccessful, if I try using the code, I get the code (everything after the &code=) paste on the box (I'm using ssh on a MAC) and click on submit, it just sends me back to the email and password authentication screen.

Can anyone help me with this?

Thanks!

**Comment by sigboe** [comment]
If you ssh into your pi, try to execute wyvern directly, I don't remember the path (I don't use a pi for gaming currently) but it is under /opt find pie-galaxy wyvern should be in there, cd into the folder for pie-galaxy, and run `./wyvern login` you can login with username and password by selecting that with the arrow keys and enter.

You can also try to paste the code= there by selecting OAuth with the arrow keys

Also you can try to login with username and password in the pie-galaxy menu

**Comment by stevenboyd78** [comment]
I was able to find the wyvern file you mentioned
```
pi@retropie:~ $ find / -iname wyvern 2>/dev/null
/opt/retropie/ports/piegalaxy/wyvern
```

Looks like the contents is an html redirect
```
pi@retropie:~ $ cat /opt/retropie/ports/piegalaxy/wyvern
<html><body>You are being <a href="https://github.com/sigboe/wyvern/releases/download/1.4.1/wyvern-1.4.1.x86">redirected</a>.</body></html>
```

I tried replacing the file with the .x86 version (just because it's what was referenced) and didn't have any luck running it.
```
pi@retropie:/opt/retropie/ports/piegalaxy $ ./wyvern login
-bash: ./wyvern: cannot execute binary file: Exec format error
```

So I replaced it with the .arm version and was able to get some output
```
pi@retropie:/opt/retropie/ports/piegalaxy $ ./wyvern login
It appears that you have not logged into GOG. Please pick a login method.
Login Method:
  OAuth Token Login
> Username/Password Login
```

I tried re-running ` ~/RetroPie/roms/ports/Pie\ Galaxy.sh` and was not able to successfully login

I tried running `.wyvern login` and attempted the user/pass option, it failed with a message about a login field
```
pi@retropie:/opt/retropie/ports/piegalaxy $ ./wyvern login
It appears that you have not logged into GOG. Please pick a login method.
Login Method: Username/Password Login
Please input your credentials.
Email: ********@*****.***
Password: [hidden]
ERROR 2021-08-02T10:09:51Z: wyvern: Could not login to GOG.
ERROR 2021-08-02T10:09:51Z: wyvern: Error: Error(MissingField("login id"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

I was able successfully login using the Oauth code option.

**Comment by sigboe** [comment]
Sorry for not dealing with this quicker, I haven't had time for a lot of things. But I fixed it due to your report @stevenboyd78 of the problem. If anyone downloaded the scriptmodule.sh file and has this problem, then they need to download the new script module and install it again. If you fixed it by your self then you don't need to reinstall

**Comment by ElyDoodson** [comment]
Has this fix been fully addressed? I seem to have the same problem logging in with cred or code. However, I'm unsure how to implement the ARM fixed mentioned. I have the latest version of the scriptmodule.sh (with the -L tag update). How can i go about logging in
